version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: full_cicd_demo
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - DATABASE_URL=sqlite:///./app.db
    volumes:
      - ./app:/app/app  # 熱重載（開發環境）
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: full_cicd_demo_network
