# Basic Test Workflow Template
# 用途：為 Python 專案建立基礎測試管線
# 執行時間：約 1-2 分鐘

name: Test

# 觸發條件
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 檢出代碼
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: 設置 Python 環境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # 根據專案需求修改

    # Step 3: 快取 pip 套件（加速執行）
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Step 4: 安裝依賴
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: 執行測試
    - name: Run tests
      run: |
        pytest -v --tb=short

    # Step 6: 產生測試摘要
    - name: Generate test summary
      if: always()
      run: |
        echo "## Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ All tests passed" >> $GITHUB_STEP_SUMMARY
