# Security Scan Workflow Template
# ç”¨é€”ï¼šå®Œæ•´çš„ä¸‰å±¤å®‰å…¨æŽƒæï¼ˆCodeQL + Snyk + Trivyï¼‰
# åŸ·è¡Œæ™‚é–“ï¼šç´„ 5-8 åˆ†é˜
# å‰ç½®éœ€æ±‚ï¼šè¨­å®š SNYK_TOKEN secret

name: Security Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * 1'  # æ¯é€±ä¸€å‡Œæ™¨ 2 é»žåŸ·è¡Œ

jobs:
  # Job 1: CodeQL éœæ…‹åˆ†æž
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python  # æ ¹æ“šå°ˆæ¡ˆä¿®æ”¹ï¼šjavascript, java, cpp, csharp, go
          queries: security-extended

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  # Job 2: Snyk ä¾è³´æŽƒæ
  snyk:
    name: Snyk Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Snyk test
        uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          command: test
        continue-on-error: true  # ä¸é˜»æ­¢ workflow

      - name: Upload Snyk results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

  # Job 3: Trivy å®¹å™¨æŽƒæï¼ˆå¦‚æžœä½¿ç”¨ Dockerï¼‰
  trivy:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # å»ºç«‹ Docker æ˜ åƒ
      - name: Build Docker image
        run: |
          docker build -t myapp:${{ github.sha }} .

      # æŽƒææ˜ åƒ
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myapp:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      # ä¸Šå‚³çµæžœåˆ° GitHub Security
      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      # å¦‚æžœæœ‰ CRITICAL æ¼æ´žï¼Œè®“ workflow å¤±æ•—
      - name: Fail on critical vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myapp:${{ github.sha }}'
          exit-code: '1'
          severity: 'CRITICAL'

  # Job 4: å®‰å…¨æŽƒæç¸½çµ
  security-summary:
    name: Security Summary
    needs: [codeql, snyk, trivy]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Generate summary
        run: |
          echo "## ðŸ”’ Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Scanner | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|---------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| CodeQL | ${{ needs.codeql.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Snyk | ${{ needs.snyk.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Trivy | ${{ needs.trivy.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Check the Security tab for detailed findings." >> $GITHUB_STEP_SUMMARY
